[package]
name = "message-box"
version = "0.1.0"
authors = ["Mark Onyango <m.onyango@optica.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = { path = "bindings" }
windows = "0.9.1"
