[package]
name = "bindings"
version = "0.1.0"
authors = ["Mark Onyango <m.onyango@optica.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.9.1"

[build-dependencies]
windows = "0.9.1"
