on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt
      
      - name: tests
        run: cargo test --all

      - name: check
        run: cargo check

      - name: fmt
        run: cargo fmt --all -- --check
        if: matrix.rust == 'stable' 
